import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const segoeuiPc = localFont({
  src: "./assets/fonts/SVN-Segoe UI.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Zalo Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={segoeuiPc.className}>{children}</body>
    </html>
  );
}
